# Jekyll Configuration

exclude: ['README.md', 'CNAME']

relative_permalinks: false

permalink: pretty

safe: true
url: http://kmikael.com

name: Mikael Konutgan
description: 'Thoughts on programming, Unix and technology'

markdown: redcarpet
